eureka:
   client:
    service-url:
        defaultZone: http://localhost:8761/eureka/



spring:
    datasource:
       url : jdbc:mysql://localhost:3306/restaurantdb #mysql-db.c3yo8caqi4fp.us-east-1.rds.amazonaws.com:3306/restaurantdb #jdbc:mysql://localhost:3306/restaurantdb
       password : root
       username :  root
       driver-class-name : com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddlauto : update
      show-sql : true
      database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
